<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrainingDataSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        DB::table('training_flashcards')->delete();
        DB::table('manual_pages')->delete();
        DB::table('training_modules')->delete();

        $this->seedModules();
        $this->seedPages();
        $this->seedFlashcards();
    }

    private function seedModules(): void
    {
        $modules = [
    ['module_key'=>'mod-1',  'title'=>'1. Welcome & Firm Overview',                         'pages'=>[1],           'description'=>'Overview of E-Tax Planner, company history, address, IRS work, error rate, guarantees, and support.', 'icon_name'=>'Building2',    'sort_order'=>1],            ['module_key'=>'mod-2',  'title'=>'2. USA Geography & Time Zones',                      'pages'=>[2,3,4],       'description'=>'United States overview, 50 states, state abbreviations, and 6 major time zones.',                     'icon_name'=>'Globe',        'sort_order'=>2],
            ['module_key'=>'mod-3',  'title'=>'3. Taxes, Tax-Free States & Local Taxes',            'pages'=>[5,6],         'description'=>'Tax definitions, 9 tax-free states, city taxes, county taxes, and city/county tax state lists.',      'icon_name'=>'DollarSign',   'sort_order'=>3],
            ['module_key'=>'mod-4',  'title'=>'4. U.S. Visa Categories & Immigration Statuses',    'pages'=>[6,7,8,9],     'description'=>'F-1, F-2, H-1B, H-4, H-4 EAD, B-1/B-2, L-1A, L-2 Visas, U.S. Citizenship, and Green Card.',        'icon_name'=>'Passport',     'sort_order'=>4],
            ['module_key'=>'mod-5',  'title'=>'5. Types of Tax Filing Status',                     'pages'=>[9,10,11,12],  'description'=>'Single (S), MFJ, MFS, Head of Household (HOH), and QWDC.',                                           'icon_name'=>'UserCheck',    'sort_order'=>5],
            ['module_key'=>'mod-6',  'title'=>'6. Taxpayer Identification (SSN & ITIN)',            'pages'=>[12,13,14],    'description'=>'Social Security Number (SSN) and ITIN rules, criteria, and application.',                             'icon_name'=>'CreditCard',   'sort_order'=>6],
            ['module_key'=>'mod-7',  'title'=>'7. Wage Statements & Tax Forms (W2, W2-C, W4, W2-G)','pages'=>[15,16],      'description'=>'W2 vs wage statements, W2-C corrections, W4 withholding certificate, and W2-G gambling winnings.',    'icon_name'=>'FileText',     'sort_order'=>7],
            ['module_key'=>'mod-8',  'title'=>'8. Filing Methods & Compliance (Paper, E-Filing, FBAR)','pages'=>[17,18],    'description'=>'Paper filing guidelines, E-filing benefits, and FBAR requirements.',                                   'icon_name'=>'Send',         'sort_order'=>8],
            ['module_key'=>'mod-9',  'title'=>'9. Healthcare & Education Forms (1095 & 1098 Series)','pages'=>[19,20],      'description'=>'Forms 1095-A, 1095-B, 1095-C, 1098, 1098-T, and 1098-E.',                                           'icon_name'=>'HeartPulse',   'sort_order'=>9],
            ['module_key'=>'mod-10', 'title'=>'10. 1099 Form Series & Retirement Savings (401k)',  'pages'=>[21,22],       'description'=>'1099-INT, 1099-DIV, 1099-MISC, 1099-NEC, 1099-SA, and 401(k) Retirement Savings Plans.',            'icon_name'=>'PieChart',     'sort_order'=>10],
            ['module_key'=>'mod-11', 'title'=>'11. Standard vs. Itemized Deductions & Schedule E', 'pages'=>[22,23],       'description'=>'2023 Standard Deduction amounts, itemized deduction categories, and Schedule E deductions.',           'icon_name'=>'Calculator',   'sort_order'=>11],
            ['module_key'=>'mod-12', 'title'=>'12. Tax Refunds, Credits, Authorizations & CPA',   'pages'=>[24,25,26],    'description'=>'Refund options, CTC, ITIN credits, Form 1040, Form 8879, Form 7216, and CPA overview.',               'icon_name'=>'ShieldCheck',  'sort_order'=>12],
        ];

        foreach ($modules as $m) {
            DB::table('training_modules')->insert([
                'module_key'  => $m['module_key'],
                'title'       => $m['title'],
                'description' => $m['description'],
                'pages'       => json_encode($m['pages']),
                'icon_name'   => $m['icon_name'],
                'sort_order'  => $m['sort_order'],
                'created_at'  => now(),
                'updated_at'  => now(),
            ]);
        }
    }

    private function seedPages(): void
    {
        $moduleMap = DB::table('training_modules')->pluck('id', 'module_key');

        $pages = [
            [1,  'mod-1',  'Welcome to E-TAX PLANNER',                    '1. Firm & CPA Overview',                    ['Welcome to E-TAX PLANNER','SUCCESSFUL 13 YEARS OF EXPERIENCE.','E- TAX Planner is a TAX Filing Firm.','It is located in CHICAGO ILLINOIS, MAPLE WOOD ROAD. 60659.','ETP work with the IRS to stay up to date on changes in the tax laws.','The tax professionals receive extensive training and work with state-of-the-art technology to ensure your taxes are done right.','We find errors in 2 out of 3 tax returns prepared by others.','Our tax professionals provide guidance and advice tailored to your occupation or tax situation to help you maximize your tax refund.','ETP Online tax preparation solutions are easy to use and backed by the expertise of E Tax Planner. E Tax Planner provides a 100% accuracy and maximum refund guarantee and includes free Audit Support (guidance and representation before the IRS) and free expert advice from the ETP community of tax specialists.']],
            [2,  'mod-2',  'Employee Training Manual USA & States Overview','2. USA Geography & Time Zones',             ['EMPLOYEE TRAINING MANUAL USA','United States, country in North America, a federal republic of 50 states. Besides the 48 conterminous states that occupy the middle latitudes of the continent, the United States includes the state of Alaska, at the northwestern extreme of North America, and the island state of Hawaii.','In United States every citizen has to report and file the taxes.','The United States has separate federal, state, and local governments with taxes imposed at each of these levels. Taxes are levied on income, payroll, property, sales, capital gains, dividends, imports, estates and gifts, as well as various fees.','USA STATES']],
            [3,  'mod-2',  'USA State Abbreviations Table',                '2. USA Geography & Time Zones',             ['USA STATE ABBREVIATIONS & CODES (50 STATES + DC)','AL - Alabama • AK - Alaska • AZ - Arizona • AR - Arkansas • CA - California','CO - Colorado • CT - Connecticut • DC - District of Columbia • DE - Delaware • FL - Florida','GA - Georgia • HI - Hawaii • ID - Idaho • IL - Illinois • IN - Indiana','IA - Iowa • KS - Kansas • KY - Kentucky • LA - Louisiana • ME - Maine','MD - Maryland • MA - Massachusetts • MI - Michigan • MN - Minnesota • MS - Mississippi','MO - Missouri • MT - Montana • NE - Nebraska • NV - Nevada • NH - New Hampshire','NJ - New Jersey • NM - New Mexico • NY - New York • NC - North Carolina • ND - North Dakota','OH - Ohio • OK - Oklahoma • OR - Oregon • PA - Pennsylvania • RI - Rhode Island','SC - South Carolina • SD - South Dakota • TN - Tennessee • TX - Texas • UT - Utah','VT - Vermont • VA - Virginia • WA - Washington • WV - West Virginia • WI - Wisconsin • WY - Wyoming']],
            [4,  'mod-2',  'US Time Zones',                                '2. USA Geography & Time Zones',             ['Large countries have many time zones because they have a large width and a vast East to West extent areas.','USA has mainly 4 time zones.','Eastern Standard Time: Major Cities: New York, Washington D.C., Atlanta, Miami.','Central Standard Time (CST): Major Cities: Chicago, Dallas, Houston, Minneapolis.','Mountain Standard Time (MST): Major Cities: Denver, Phoenix, Salt Lake City, Albuquerque.','Pacific Standard Time (PST): Major Cities: Los Angeles, San Francisco, Seattle, Portland.','Additionally, there are two more time zones in the U.S. that cover Alaska and Hawaii:','Alaska Time Zone (AKT): Major Cities: Anchorage, Fairbanks.','Hawaii-Aleutian Time Zone (HAST): Major Cities: Honolulu, Hilo.']],
            [5,  'mod-3',  'Taxes, Tax-Free States, and City Taxes',       '3. Taxes, Tax-Free States & Local Taxes',   ['TAXES','The United States has separate federal, state, and local governments with taxes imposed at each of these levels.','TAX-FREE STATES','There are 9 tax free states in USA:','• AK - Alaska','• FL - Florida','• NH - New Hampshire','• NV - Nevada','• SD - South Dakota','• TN - Tennessee','• TX - Texas','• WA - Washington','• WY - Wyoming','CITY TAXES','Tax imposed, and collected or administered, by the city. "City tax" does not include a tax imposed upon real property under the Illinois Property Tax Code or fees collected by the City, except, however, that "City tax" does include the City\'s infrastructure maintenance fees.']],
            [6,  'mod-3',  'County Taxes, City/County States & F-1 Visa', '3. Taxes, Tax-Free States & Local Taxes',   ['COUNTY TAXES','A county tax is a property tax levied by the county to fund things like law enforcement, public education, and road maintenance.','CITY & COUNTY TAX STATES','CITY TAXES: MI - MICHIGAN, NY - NEW YORK, PA - PENNSYLVANIA, OH - OHIO, KY - KENTUCKY','COUNTY TAXES: IN - INDIANA, MD - MARYLAND, IA - IOWA','U.S.A VISA CATEGORY & TYPES','F-1 Visa:','The F-1 Visa is a non-immigrant visa category for individuals who wish to enter the United States to pursue academic studies at an accredited institution.','• On-Campus Employment: F-1 students can work on-campus up to 20 hours per week during the academic term and full-time during breaks.','• Off-Campus Employment: After completing the first academic year, students may apply for off-campus employment authorization through CPT or OPT. OPT allows students to work for up to 12 months (or 24 months for STEM graduates) in a field related to their degree.']],
            [7,  'mod-4',  'F-2, H-1B, and H-4 Visas',                   '4. U.S. Visa Categories',                   ['F-2 Visa: The F-2 Visa is a non-immigrant visa for the dependents of F-1 student visa holders.','• Employment: F-2 visa holders are not permitted to work in the U.S. They cannot engage in any form of employment, whether on-campus or off-campus.','H-1B Visa:','• The H-1B Visa is a non-immigrant visa category that allows U.S. employers to temporarily employ foreign workers in specialty occupations.','• It is designed for fields that typically require a bachelor\'s degree or higher. Often used for IT, engineering, medicine, and business.','H-4 Visa:','• The H-4 Visa is a non-immigrant visa for the dependents of H-1B visa holders. It allows spouses and unmarried children under 21 to live in the United States.']],
            [8,  'mod-4',  'H-4 EAD, B-1/B-2, and L-1A Visas',          '4. U.S. Visa Categories',                   ['H-4 EAD: The H-4 EAD (Employment Authorization Document) is a work permit available to certain dependents of H-1B visa holders, specifically those on H-4 visas. It allows eligible H-4 visa holders to legally work in the United States.','B-1 Visa & B-2 Visa: Temporary Visa for Business Travelers and a domestic servant.','• The B-2 Visa is for tourism and visiting purposes. Temporary Visitor for Pleasure or Medical Treatment.','L-1A Visa: The L-1A Visa is a non-immigrant visa designed for intra-company transferees who are executives or managers. It allows multinational companies to transfer these individuals from a foreign office to a U.S. office.']],
            [9,  'mod-4',  'L-2 Visa, Citizen, and Green Card',           '4. U.S. Visa Categories',                   ['L-2 Visa: The L-2 Visa is a non-immigrant visa issued to the dependents of L-1 visa holders, specifically spouses and unmarried children under the age of 21.','Citizen: Who has born in US will be a Citizen. U.S. citizenship provides individuals with significant rights and privileges, but also comes with responsibilities and obligations.','Green Card: A Green Card holder (permanent resident) is someone who has been granted authorization to live and work in the United States on a permanent basis. The Green Card provides a potential pathway to U.S. citizenship.']],
            [10, 'mod-5',  'Filing Statuses: Single & Married Filing Jointly','5. Types of Tax Filing Status',          ['In the context of U.S. income taxes, filing status refers to the category under which you file your federal income tax return.','Single (S) - You must file as single if you are unmarried. Single filers include people who are unmarried or legally separated from a spouse under a divorce or separate maintenance decree on the last day of the year.','Married Filing Jointly (MFJ) - If you are married, TP and SP agree to file together. On a joint return, you need to report your combined income and deduct your combined allowable expenses.','When using the married filing jointly filing status, both spouses are equally responsible for the return and the taxes. If either one understates the taxes due, both are equally liable for the penalties.','Married Filing Separately (MFS) -']],
            [11, 'mod-5',  'Filing Statuses: MFS & Head of Household',    '5. Types of Tax Filing Status',             ['• If TAXPAYER is married. This method may benefit you if you want to be responsible only for your own tax.','Married filing separately is a tax status for married couples who choose to record their respective incomes, exemptions, and deductions on separate tax returns.','Head of Household (HOH) - If TAXPAYER pay more than half of the home expenses and have more income with dependents can file for (HOH).','Criteria for HOH: • Your spouse did not live with you for the last six months of the year. • You provided the main home of the qualifying child and paid for more than half the home costs. • You are claiming your child as a dependent.','Claiming "head of household" as your filing status benefits you in two ways. First, you\'ll get a lower tax rate.']],
            [12, 'mod-5',  'QWDC & Social Security Number (SSN)',         '5. Types of Tax Filing Status',             ['Qualifying Widower With Dependent Child (QWDC) - You may file as a qualifying widow or widower for the next two years beginning the year after your spouse\'s death, and your dependents must stay with you for at least six months.','The survivor must remain unmarried for at least two years following the year of the spouse\'s death. The taxpayer must have at least one dependent child and have handled at least half of the household costs.','The qualifying widow(er) status offers the same standard deduction amount and tax bracket ranges as those for married couples who file jointly.','(SSN) Social Security Number - SSN stands for Social Security Number. It is a unique nine-digit number assigned to U.S. citizens, permanent residents, and certain non-residents.']],
            [13, 'mod-6',  'SSN Purpose & ITIN Overview',                 '6. Taxpayer Identification (SSN & ITIN)',   ['SSN Purpose: ❖ Identification: Used as a unique identifier. ❖ Social Security Benefits: Essential for retirement, disability, and survivor benefits. ❖ Tax Reporting: Required for income tax filing, used by the IRS to track earnings and tax obligations.','(ITIN) Individual Taxpayer Identification Number - ITIN stands for Individual Taxpayer Identification Number. It is a nine-digit number used to claim your dependents and spouse on your tax return.','❖ Structure: The ITIN is composed of nine digits formatted as XXX-XX-XXXX. It always begins with the number 9.','Renewal and Expiration:']],
            [14, 'mod-6',  'ITIN Expiration, Criteria & Application',     '6. Taxpayer Identification (SSN & ITIN)',   ['❖ Expiration: ITINs can expire if not used on a federal tax return for three consecutive years. An expired ITIN must be renewed before it can be used again.','Criteria to apply ITIN - • A spouse must spend at least 1 to 90 days in the United States to claim a tax year. • Child dependents should be in the US for at least 183 days to claim a tax year.','How to apply ITIN? • A passport front and back copy, a visa copy, and the applicant\'s basic information are all required. • The W7 form is an application form attached to the 1040 (federal documents). • TP must schedule an appointment by calling or visiting the nearest TAC (TAXPAYER ASSISTANCE CENTER) office. • To receive an ITIN, it takes at least 6 to 8 weeks from the IRS.']],
            [15, 'mod-7',  'W2 Wage Statement & W2-C Corrected Statement','7. Wage Statements & Tax Forms',            ['W2 - Wage Statement: A wage and earnings statement should not be confused with a W-2 form. The former is a breakdown of your wages for the pay period, and the latter is your annual wage and tax statement.','W2-C Corrected Wage Statement: A W-2c form is an IRS tax document used to correct or amend a W-2. Corrections include: incorrect employee name, wrong Social Security number, incorrect address, incorrect tax year, error on employer identification number (EIN), incorrect earnings or tax withholdings.']],
            [16, 'mod-7',  'W4 Form & W2-G Gambling Winnings',            '7. Wage Statements & Tax Forms',            ['W4 Form: Form W-4 is filled out by employees to indicate their tax situation to their employer. The W-4 form tells the employer the amount of tax to withhold based on marital status, number of allowances and dependents, and other factors.','Increasing the number of allowances on the form decreases the amount of money withheld from the paycheck.','W2-G: File this form to report gambling winnings and any federal income tax withheld on those winnings. Key information: • Reportable winnings: gross winnings. • Date won: date of the winning event, not payment date. • Type of wager: Daily Double, Big Triple, or Pick 6.']],
            [17, 'mod-8',  'Paper Filing vs. E-Filing',                   '8. Filing Methods & Compliance',            ['Paper Filing: Taxpayers can fill out tax forms by hand and mail them to the IRS or state tax authorities. Make sure names, addresses and Social Security numbers are correct. Check data entry and math. Sign and date your return.','E - Filing: Electronic filing is the process of submitting tax returns via the Internet. It allows taxpayers to file taxes online at their convenience and speeds up refunds while reducing errors.','The tax filer receives an acceptance or rejection notice within 48 hours—usually within 24 hours—of transmitting the tax return. Acceptance is proof that the documents have been received.']],
            [18, 'mod-8',  'F-BAR (Foreign Bank Account Report)',          '8. Filing Methods & Compliance',            ['F - BAR - (Foreign Bank Account Report): U.S. persons (U.S. citizens, Green Card holders, resident aliens, and dual citizens) are required to file an FBAR if the combined balance of all foreign accounts is more than $10,000 at any point during the calendar year.','Financial interest is determined based upon who is the owner of record or legal title. Signature authority means you have control over the disposition of assets through direct communication with the institution.','Types of Accounts to Report: Bank Accounts, Investment Accounts, Other Financial Accounts.']],
            [19, 'mod-9',  'Important Health Insurance Forms (1095 Series)','9. Healthcare & Education Forms',          ['1095 (A) - Health Insurance Marketplace Statement: Used to report information about health insurance coverage obtained through the Health Insurance Marketplace under the ACA. Crucial for reconciling premium tax credits.','1095 (B) - Health Coverage form: Used by insurers and government programs to confirm that the individual had minimum essential coverage under the ACA for each month of the year.','1095(C) - Employer-Provided Health Insurance Offer and Coverage form: Used to report information about health insurance coverage offered by employers under the ACA employer mandate.']],
            [20, 'mod-9',  'Mortgage, Tuition & Student Loan (1098 Series)','9. Healthcare & Education Forms',          ['1098 - Home Mortgage Documents: A home mortgage document given when property is purchased on loan. The 1098 Form reports mortgage interest paid to claim deductions on Schedule A.','1098 (T) - Tuition Fee Document F1 to H1b only: Reports information on tuition expenses billed at a college or university. Used to claim education credits such as the American Opportunity Credit and the Lifetime Learning Credit.','Form 1098 (E) - Student Loan Interest Statement: Reports interest paid on student loans during the tax year. Used to claim a student loan interest deduction on Form 1040.']],
            [21, 'mod-10', '1099 Forms Series & HSA Statements',          '10. 1099 Form Series & Retirement Savings',  ['1099 Form series is used to report various types of income. Form 1099-INT: reports interest income. Form 1099-DIV: issued if you received more than $10 in dividends from a corporation. Form 1099-MISC: reports miscellaneous income such as rent, royalties, prizes, awards. Form 1099-NEC: reports payments of $600 or more to non-employees for services provided.','1099 (SA) - Health Savings Account: The 1099-SA Form reports distributions from Health Savings Accounts (HSAs), Archer Medical Savings Accounts (MSAs), or Medicare Advantage MSAs.']],
            [22, 'mod-10', '401k & Standard Deduction Amounts (2023)',    '11. Standard vs. Itemized Deductions',      ['401 k - Retirement Savings Plan: Retirement savings plan sponsored by an employer. It lets workers save and invest a piece of their paycheck before taxes are taken out. Taxes aren\'t paid until the money is withdrawn from the account.','Standard and Itemized Deductions: Standard deduction is a fixed dollar amount that taxpayers can subtract from their taxable income.','Amounts for Tax Year 2023: ❖ Single Filers: $13,850 ❖ Married Filing Jointly: $27,700 ❖ Head of Household: $20,800 ❖ Married Filing Separately: $13,850 ❖ Qualifying Widow(er): $27,700']],
            [23, 'mod-11', 'Itemized Deductions & Schedule E',            '11. Standard vs. Itemized Deductions',      ['Itemized deductions are specific expenses that you can deduct from your gross income. Reported on Schedule A of Form 1040.','Common Itemized Deductions: • Medical and Dental Expenses • State and Local Taxes • Mortgage Interest • Charitable Contributions • Casualty and Theft Losses • Miscellaneous Deductions','Schedule E is a form used to report income and expenses from rental property, royalties, estates, and trusts. Common Schedule-E deductions: Mortgage Interest, Property Taxes, Insurance Premiums, Repairs and Maintenance, Depreciation, Management Fees, Advertising, Legal and Professional Fees.']],
            [24, 'mod-12', 'Refunds, Tax Owed & Child Tax Credit (CTC)',  '12. Tax Refunds, Credits & Authorizations', ['Refunds & Owe: Refunds occur when total tax payments exceed actual tax liability. Receiving Your Refund: • Direct Deposit: Faster processing. • Check: Paper check mailed to your address. • Apply to Next Year: Applied as estimated payment.','CHILD TAX CREDIT: The Child Tax Credit (CTC) is a federal tax benefit designed to reduce the tax burden on families with children. If the child has an SSN, he will get a different type of credit. If the child has ITIN, he will get a different type of amount credit.']],
            [25, 'mod-12', 'ITIN Credits, Form 1040, Form 8879 & Form 7216','12. Tax Refunds, Credits & Authorizations',['ITIN Credits: For the Child Tax Credit, a qualifying child must have a valid SSN. If a taxpayer uses an ITIN, they generally cannot claim the Child Tax Credit. Exception: Credit for Other Dependents (up to $500 per qualifying dependent) is available to taxpayers with ITINs.','1040 - Tax Return: Form 1040 is an IRS tax form used for personal federal income tax returns. It calculates the total taxable income and determines how much is to be paid or refunded.','Form 8879: Declaration document and signature authorization for an e-filed return filed by an electronic return originator (ERO). It is E-Filing authorization document.','Form 7216: Authorization to file the taxes on behalf of the client.']],
            [26, 'mod-12', 'CPA & How E-Tax Planner Works',               '12. Tax Refunds, Credits & Authorizations', ['Who is our CPA -(Certified Public Accountant): Our CPA is MR.JOBY THOMAS who is Retired from IRS. After his retirement he started his own Firm as E- TAX Planner. We are in the Market from past 12 Years.','How does it works - • We help the TAX Payers to pay their taxes and get their refunds. • We provide Free TAX estimation. • We also Provide Referral Bonus for those who provide Reference.','***************THANK YOU***************']],
        ];

        foreach ($pages as $p) {
            [$num, $modKey, $title, $modTitle, $text] = $p;
            $modId = $moduleMap[$modKey] ?? null;
            DB::table('manual_pages')->insert([
                'module_id'     => $modId,
                'page_number'   => $num,
                'title'         => $title,
                'module_title'  => $modTitle,
                'verbatim_text' => json_encode($text),
                'created_at'    => now(),
                'updated_at'    => now(),
            ]);
        }
    }

    private function seedFlashcards(): void
    {
        $cards = [
          ['card-p1-1','mod-1',1,'E-Tax Planner Firm Location','Where is E-TAX PLANNER located and what is its experience duration?','It is located in CHICAGO ILLINOIS, MAPLE WOOD ROAD. 60659. SUCCESSFUL 13 YEARS OF EXPERIENCE.','Firm Overview',['CHICAGO ILLINOIS','MAPLE WOOD ROAD. 60659','13 YEARS OF EXPERIENCE']],
          ['card-p1-2','mod-1',1,'E-Tax Planner Error Rate & Guarantees','What error rate does ETP find in returns prepared by others, and what guarantees does ETP provide?','We find errors in 2 out of 3 tax returns prepared by others. E Tax Planner provides a 100% accuracy and maximum refund guarantee and includes free Audit Support and free expert advice.','Firm Guarantees',['2 out of 3 tax returns','100% accuracy and maximum refund guarantee','free Audit Support']],
          ['card-p3-1','mod-2',3,'USA State Abbreviations & Total Count','How many state abbreviations are listed in the USA State Abbreviations Table, and what are the postal codes for CA, NY, TX, FL, and IL?',"There are 50 states plus DC listed.\n• CA - California\n• NY - New York\n• TX - Texas\n• FL - Florida\n• IL - Illinois",'State Abbreviations',['50 states plus DC','CA - California','NY - New York','TX - Texas','FL - Florida','IL - Illinois']],
          ['card-p4-1','mod-2',4,'USA Main Time Zones & Major Cities','What are the main time zones in the USA and their major cities?',"USA has mainly 4 time zones.\n• Eastern Standard Time: New York, Washington D.C., Atlanta, Miami.\n• Central Standard Time (CST): Chicago, Dallas, Houston, Minneapolis.\n• Mountain Standard Time (MST): Denver, Phoenix, Salt Lake City, Albuquerque.\n• Pacific Standard Time (PST): Los Angeles, San Francisco, Seattle, Portland.\nAlso: Alaska Time Zone (AKT): Anchorage, Fairbanks; Hawaii-Aleutian Time Zone (HAST): Honolulu, Hilo.",'Time Zones',['Eastern Standard Time','Central Standard Time (CST)','Mountain Standard Time (MST)','Pacific Standard Time (PST)','Alaska Time Zone (AKT)','Hawaii-Aleutian Time Zone (HAST)']],
          ['card-p5-1','mod-3',5,'List of 9 Tax-Free States in USA','What are the 9 tax free states in USA?',"There are 9 tax free states in USA:\n• AK - Alaska\n• FL - Florida\n• NH - New Hampshire\n• NV - Nevada\n• SD - South Dakota\n• TN - Tennessee\n• TX - Texas\n• WA - Washington\n• WY - Wyoming",'Tax-Free States',['AK - Alaska','FL - Florida','NH - New Hampshire','NV - Nevada','SD - South Dakota','TN - Tennessee','TX - Texas','WA - Washington','WY - Wyoming']],
          ['card-p6-1','mod-3',6,'City Taxes States vs County Taxes States','Which states have City Taxes and which states have County Taxes?',"CITY TAXES: MI - MICHIGAN, NY - NEW YORK, PA - PENNSYLVANIA, OH - OHIO, KY - KENTUCKY\nCOUNTY TAXES: IN - INDIANA, MD - MARYLAND, IA - IOWA",'City & County Taxes',['MI, NY, PA, OH, KY','IN, MD, IA']],
          ['card-p6-2','mod-4',6,'F-1 Visa Employment Rules','What are the employment rules for F-1 Visa holders regarding on-campus and off-campus work?',"• On-Campus: up to 20 hours per week during academic term and full-time during breaks.\n• Off-Campus: After first academic year, apply through CPT or OPT. OPT allows up to 12 months (or 24 months for STEM graduates).",'Visa Rules',['20 hours per week','full-time during breaks','CPT or OPT','12 months (or 24 months for STEM graduates)']],
          ['card-p7-1','mod-4',7,'F-2 Visa Work Rules','Are F-2 Visa holders permitted to work in the United States?','F-2 visa holders are not permitted to work in the U.S. They cannot engage in any form of employment, whether on-campus or off-campus.','Visa Rules',['not permitted to work','whether on-campus or off-campus']],
          ['card-p7-2','mod-4',7,'H-1B Visa Definition','What is the H-1B Visa category designed for?','The H-1B Visa is a non-immigrant visa category that allows U.S. employers to temporarily employ foreign workers in specialty occupations that typically require a bachelor\'s degree or higher.','Visa Rules',['specialty occupations','bachelor\'s degree or higher']],
          ['card-p8-1','mod-4',8,'H-4 EAD Definition','What is the H-4 EAD and who is eligible for it?','The H-4 EAD (Employment Authorization Document) is a work permit available to certain dependents of H-1B visa holders, specifically those on H-4 visas. It allows eligible H-4 visa holders to legally work in the United States.','Visa Rules',['Employment Authorization Document','dependents of H-1B visa holders','legally work in the United States']],
          ['card-p10-1','mod-5',10,'Single Filing Status Criteria','Who qualifies for the Single (S) tax filing status?','You must file as single if you are unmarried. Single filers include people who are unmarried or legally separated from a spouse under a divorce or separate maintenance decree on the last day of the year and who do not qualify for another filing status.','Filing Status',['unmarried','legally separated','divorce or separate maintenance decree']],
          ['card-p10-2','mod-5',10,'Married Filing Jointly (MFJ) Liability Rule','On a Married Filing Jointly return, how is tax liability shared between spouses?','Both spouses are equally responsible for the return and the taxes. If either one understates the taxes due, both are equally liable for the penalties, unless the other spouse can prove they were unaware of the mistake and did not benefit from it.','Filing Status',['both spouses are equally responsible','equally liable for the penalties','unaware of the mistake']],
          ['card-p11-1','mod-5',11,'Head of Household (HOH) 3 Key Criteria','What three criteria must a married person filing separately meet to claim Head of Household (HOH) status?',"1. Your spouse did not live with you for the last six months of the year.\n2. You provided the main home of the qualifying child and paid for more than half the home costs.\n3. You are claiming your child as a dependent.",'Filing Status',['did not live with you for the last six months','paid for more than half the home costs','claiming your child as a dependent']],
          ['card-p12-1','mod-5',12,'Qualifying Widower With Dependent Child (QWDC)','What are the rules for filing as Qualifying Widower With Dependent Child (QWDC)?','You may file as a qualifying widow or widower for the next two years beginning the year after your spouse\'s death, and your dependents must stay with you for at least six months. The survivor must remain unmarried for at least two years. The taxpayer must have at least one dependent child and have handled at least half of the household costs.','Filing Status',['next two years','at least six months','remain unmarried for at least two years','half of the household costs']],
          ['card-p13-1','mod-6',13,'ITIN Definition & Structure','What is an ITIN, what is its purpose, and what number does it always start with?','ITIN stands for Individual Taxpayer Identification Number. It is a nine-digit number used to claim your dependents and spouse on your tax return. Formatted as XXX-XX-XXXX. It always begins with the number 9.','Taxpayer ID',['Individual Taxpayer Identification Number','not eligible for SSN','formatted as XXX-XX-XXXX','begins with the number 9']],
          ['card-p14-1','mod-6',14,'Criteria to Apply for ITIN','What are the US stay criteria for a spouse and child dependent to apply for an ITIN?',"• A spouse must spend at least 1 to 90 days in the United States to claim a tax year.\n• Child dependents should be in the US for at least 183 days to claim a tax year.",'ITIN Criteria',['spouse must spend at least 1 to 90 days','Child dependents should be in the US for at least 183 days']],
          ['card-p14-2','mod-6',14,'How to Apply for ITIN & Processing Time','How do you apply for an ITIN, what form is attached, and how long does it take from the IRS?',"• A passport front and back copy, a visa copy, and the applicant's basic information are required.\n• The W7 form is attached to the 1040 (federal documents).\n• TP must schedule an appointment at the nearest TAC (TAXPAYER ASSISTANCE CENTER) office.\n• To receive an ITIN, it takes at least 6 to 8 weeks from the IRS.",'ITIN Application',['passport front and back copy','W7 form attached to 1040','TAC (TAXPAYER ASSISTANCE CENTER)','takes at least 6 to 8 weeks']],
          ['card-p15-1','mod-7',15,'W-2 vs. Wage Statement & W-2c Purpose','What is the difference between a wage statement and a W-2 form, and what is Form W-2c used for?','A wage statement is a breakdown of your wages for the pay period, while a W-2 is your annual wage and tax statement. A W-2c is used to correct errors on a W-2 such as incorrect names, amounts, or Social Security numbers.','Wage Statements',['breakdown of wages for the pay period','annual wage and tax statement','correct or amend a W-2']],
          ['card-p16-1','mod-7',16,'W-4 Allowances Effect','How does increasing allowances on Form W-4 affect paycheck withholding?','Increasing the number of allowances on the form decreases the amount of money withheld from the paycheck.','Tax Withholding',['increasing the number of allowances','decreases the amount of money withheld']],
          ['card-p17-1','mod-8',17,'E-Filing Notification Timelines','How quickly does a tax filer receive an acceptance or rejection notice when E-Filing?','The tax filer receives an acceptance or rejection notice within 48 hours—usually within 24 hours—of transmitting the tax return. Acceptance is proof that the documents have been received and are in the system.','E-Filing',['within 48 hours—usually within 24 hours','Acceptance is proof','rejection alerts the taxpayer']],
          ['card-p18-1','mod-8',18,'FBAR Filing Threshold & Account Types','Who must file an FBAR and what is the combined account balance threshold?','U.S. persons (U.S. citizens, Green Card holders, resident aliens, and dual citizens) are required to file an FBAR if the combined balance of all foreign accounts is more than $10,000 at any point during the calendar year. Types: Bank Accounts, Investment Accounts, Other Financial Accounts.','FBAR Compliance',['more than $10,000 at any point during the calendar year','financial interest or signature authority','Bank Accounts, Investment Accounts']],
          ['card-p19-1','mod-9',19,'1095-A, 1095-B, and 1095-C Differences','What are the distinct purposes of Form 1095-A, Form 1095-B, and Form 1095-C?',"• 1095-A: Marketplace Statement – reconcile premium tax credits.\n• 1095-B: Health Coverage – confirm minimum essential coverage.\n• 1095-C: Employer-Provided Health Insurance – report employer mandate compliance.",'Health Insurance Forms',['1095-A Marketplace Statement','1095-B Health Coverage','1095-C Employer-Provided']],
          ['card-p20-1','mod-9',20,'1098-T Tuition Fee Document Scope','What is Form 1098-T used for and what visa restriction is stated for it in the manual?','1098 (T) - Tuition Fee Document F1 to H1b only. The 1098-T form reports tuition expenses billed at a college or university. Used to claim education credits such as the American Opportunity Credit and the Lifetime Learning Credit.','Education Forms',['F1 to H1b only','tuition expenses','American Opportunity Credit','Lifetime Learning Credit']],
          ['card-p21-1','mod-10',21,'Form 1099-DIV & 1099-NEC Thresholds','What are the reporting dollar thresholds for Form 1099-DIV and Form 1099-NEC?',"• Form 1099-DIV: Issued if you received more than $10 in dividends.\n• Form 1099-NEC: Issued for payments of $600 or more to non-employees.",'1099 Forms',['more than $10 in dividends','$600 or more to non-employees']],
          ['card-p22-1','mod-10',22,'401(k) Retirement Savings Plan Definition','How does a 401(k) Retirement Savings Plan work according to the manual?','Retirement savings plan sponsored by an employer. It lets workers save and invest a piece of their paycheck before taxes are taken out. Taxes aren\'t paid until the money is withdrawn from the account.','Retirement Plans',['sponsored by an employer','before taxes are taken out','Taxes aren\'t paid until withdrawn']],
          ['card-p22-2','mod-11',22,'Standard Deduction Amounts for Tax Year 2023','What are the exact 2023 Standard Deduction amounts for all filing statuses?',"Amounts for Tax Year 2023:\n❖ Single Filers: $13,850\n❖ Married Filing Jointly: $27,700\n❖ Head of Household: $20,800\n❖ Married Filing Separately: $13,850\n❖ Qualifying Widow(er): $27,700",'Standard Deductions',['Single Filers: $13,850','Married Filing Jointly: $27,700','Head of Household: $20,800','Married Filing Separately: $13,850','Qualifying Widow(er): $27,700']],
          ['card-p23-1','mod-11',23,'Schedule E Purpose & Common Deductions','What is Schedule E used for and what are common Schedule-E deductions?','Schedule E reports income and expenses from rental property, royalties, estates, and trusts (Form 1040 attachment). Common deductions: Mortgage Interest, Property Taxes, Insurance Premiums, Repairs and Maintenance, Depreciation, Management Fees, Advertising, Legal and Professional Fees.','Deductions',['rental property, royalties, estates, and trusts','Depreciation','Management Fees','Repairs and Maintenance']],
          ['card-p24-1','mod-12',24,'Receiving Your Tax Refund Options','What three methods can a taxpayer choose to receive their refund?',"• Direct Deposit: Directly deposited into your bank account for faster processing.\n• Check: Paper check mailed to your address.\n• Apply to Next Year: Applied as an estimated payment for the next year's taxes.",'Tax Refunds',['Direct Deposit','Check','Apply to Next Year']],
          ['card-p25-1','mod-12',25,'ITIN Credits & Child Tax Credit Rules','Can taxpayers using an ITIN claim the Child Tax Credit, and what exception exists?','A qualifying child must have a valid SSN to claim the Child Tax Credit. If a taxpayer uses an ITIN, they generally cannot claim the Child Tax Credit. Exception: The Credit for Other Dependents (up to $500 per qualifying dependent) is available to taxpayers with ITINs.','Tax Credits',['qualifying child must have a valid SSN','cannot claim the Child Tax Credit','Credit for Other Dependents (up to $500 per qualifying dependent)']],
          ['card-p25-2','mod-12',25,'Form 8879 and Form 7216 Definitions','What are Form 8879 and Form 7216 used for?',"• Form 8879: Declaration document and signature authorization for an e-filed return (ERO). E-Filing authorization document.\n• Form 7216: Authorization to file the taxes on behalf of the client.",'Tax Authorizations',['Form 8879 signature authorization for an e-filed return','Form 7216 authorization to file the taxes on behalf of the client']],
          ['card-p26-1','mod-12',26,'Who is E-Tax Planner CPA?','Who is the CPA of E-Tax Planner and what is his background?','Our CPA is MR.JOBY THOMAS who is Retired from IRS. After his retirement he started his own Firm as E- TAX Planner. We are in the Market from past 12 Years.','Firm CPA',['MR.JOBY THOMAS','Retired from IRS','past 12 Years']],
        ];

        foreach ($cards as $c) {
            [$key,$modKey,$page,$title,$prompt,$answer,$category,$terms] = $c;
            DB::table('training_flashcards')->insert([
                'card_key'              => $key,
                'module_key'            => $modKey,
                'page_number'           => $page,
                'title'                 => $title,
                'prompt'                => $prompt,
                'exact_answer_text'     => $answer,
                'exact_context_snippet' => $answer,
                'category'              => $category,
                'key_terms'             => json_encode($terms),
                'created_at'            => now(),
                'updated_at'            => now(),
            ]);
        }
    }
}
