<!DOCTYPE html>
<html>
<head>
    <title>Sample Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .content {
            line-height: 1.6;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sample Report</h1>
        <p>Report ID: {{ $reportId }}</p>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
    </div>
    
    <div class="content">
        <h2>Report Summary</h2>
        <p>This is a sample report generated by the system. In a real implementation, this would contain actual data based on the report type and parameters.</p>
        
        <h3>Key Metrics</h3>
        <ul>
            <li>Total Records: 100</li>
            <li>Success Rate: 95%</li>
            <li>Processing Time: 2.5 seconds</li>
        </ul>
        
        <h3>Recommendations</h3>
        <p>Based on the analysis, we recommend continuing with the current approach while monitoring key performance indicators.</p>
    </div>
    
    <div class="footer">
        <p>This report was automatically generated by the system.</p>
    </div>
</body>
</html>